version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "monthly"
