name: expanded_grid
description: An unscrollable Grid View.
version: 1.0.0
# author: fastriver_org
homepage: https://github.com/organic-nailer/expanded_grid

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
